### PR TITLE
Katy's revisions and questions

### PR DESCRIPTION
**Pull request by kawilliams**
@alex-r-bigelow here are my revisions. What's informants.csv?

### CODE REVIEW

**Review by alex-r-bigelow — APPROVED** [review]
Thanks; huge fan of these changes!

**Comment by kawilliams** [comment]
Great, thanks!

**Comment by alex-r-bigelow** [comment]
(You're definitely faster than me, but for the sake of documentation):

Informants.csv is essentially meant to copy Muller et al. [1]'s Table 1—I'm expecting somewhere around 20ish entries from my end in the immediate future. Comments / ideas are welcome (i.e. is the Sex column important—and shouldn't it be "Gender?" It seems standard to include this in a lot of HCI papers, and does hint at the diversity of the people we're talking to without revealing too much that could be identifying...).

[1] Muller, M., Lange, I., Wang, D., Piorkowski, D., Tsay, J., Liao, Q. V., ... & Erickson, T. (2019, May). How Data Science Workers Work with Data: Discovery, Capture, Curation, Design, Creation. In Proceedings of the 2019 CHI Conference on Human Factors in Computing Systems (pp. 1-15).

**Comment by kawilliams** [comment]
I recognized the table once I looked at it, but figured I'd add a quick description. 

In the paper when describing Muller et al. [1]'s Table 1, the authors do put that they use Sex and not Gender because "those data are considered sensitive personal information" and could put some workers in different countries at risk. 

I generally support Gender rather than Sex in this case since I think we have a large and diverse enough pool of survey respondents that it is impossible to identify a person, unless someone provides a very specific job title

**Comment by kisaacs** [comment]
Why include either?

**Comment by alex-r-bigelow** [comment]
I'm happy to remove that column

**Pull request merged**
