### PR TITLE
Text-based data codes and groups/network codes

### PR DESCRIPTION
**Pull request by kawilliams**
Forgot to make a new branch, sorry. Some of this is new, but most of these additions are related to things we discussed Thursday 2/27 and I went back and found the supporting responses

### CODE REVIEW

**Review by alex-r-bigelow — APPROVED** [review]
These are really interesting; thanks for adding them! I'm excited to integrate these on Thursday.

Feel free to merge now, ... or later, depending on how you prefer to work.

**Comment by kawilliams** [comment]
We'll talk Thursday and then I'll close the branch. Thanks!

**Comment by alex-r-bigelow** [comment]
I've added stuff from Thursday's meeting. Two things that need attention:

1. I took the liberty of adding numbers to codes to enable linking codes to categories. I'm happy to revert this if there are objections
2. Each of the categories has nuance, particularly the first one where I think I failed to capture what was said. I flagged this in `codes.md` with a `TODO` for now—feedback on this before merging would be appreciated

**Review by alex-r-bigelow — APPROVED** [review]
This looks great! I know @kisaacs is pretty busy; maybe we should just merge this and leave the TODO in `codes.md` so that we can start branching from master again?

**Comment by kawilliams** [comment]
Sounds good

**Pull request merged**
