### PR TITLE
More evidence, reworked categories

### PR DESCRIPTION
**Pull request by alex-r-bigelow**

### CODE REVIEW

**Comment by kawilliams** [comment]
Some codes discussed offline are listed as category support (without the code description listed in this document):
INTUITION_ABOUT_GROUPS
LATENT_WRANGLING_OR_ABSTRACTION
EMOTIONS_ABOUT_DATA_ABSTRACTIONS 
HARD_TO_ISOLATE_DESIGN_FROM_OTHER_CONCERNS
MEDIA_TOO_UNDEFINED
SHOWING_RAW_DATA_HELPS_COMMUNICATION

*I think I caught them all

What was the reasoning behind adding MANY_VERY_INACCURATE_RESPONSES as support for the "Latent data abstractions are very common" category?

**Comment by alex-r-bigelow** [comment]
This is a really good point—we really should write out *why* each of the codes support each category. I've kind of started this process in the paper itself, but maybe it makes more sense to do it here first where it doesn't have to fit in paragraphs yet.

For example, I think the MANY_VERY_INACCURATE_RESPONSES helps set up part of the "Latent data abstractions are very common" story, in that it implies that, at least initially, the raw data wasn't designed to support many of the perspectives that we introduced. Although maybe I'm playing a little fast with what we want "latent abstraction" to mean... we defined it as:

"A meaningful, useful abstraction of the data is possible yet not fully communicated, or even thought out"

If someone *has* fully thought out their data / communicated it in terms of abstraction category X, could X still be considered "latent" if the raw data still hasn't been wrangled to a shape that the person would describe as X? If yes, we should probably modify our definition; if no, I really shouldn't be using MANY_VERY_INACCURATE_RESPONSES as support for this category.

**Comment by kawilliams** [comment]
Ha thanks for updating "meta-abstraction" to "typology". Do we want to merge and close this branch before it turns into an invasive vine?

**Comment by alex-r-bigelow** [comment]
Sure, that makes sense; I'll merge this now. I think a few things should be updated here as we write the paper, but that can be its own PR

**Pull request merged**
